### ISSUE TITLE
"file.isDirectory is not a function" introduced in 1.6.0

### ISSUE THREAD

**Issue by heph** [jonschlinkert/parser-front-matter#4]
After upgrading from 1.5.0 to 1.6.0 started getting the following exceptions in... well, somewhere:

```
Running "assemble" task
Building "page": website/en_US/**/*.hbs
Error running middleware for website/en_US/index
TypeError: file.isDirectory is not a function
```

Tracked it down to this module's release of 1.6.0 last night. Pinned version 1.5.0 and the error went away. Honestly not sure how to find _what's_ calling this, but crossing my fingers you can figure out a way to fix it :-)

**Comment by jonschlinkert** [comment]
Yeah I know what the issues is. I thought I pushed up a fix for that. Did you try clearing everything out of node_modules and reinstalling?

**Comment by jonschlinkert** [comment]
Sorry @heph I found it and fixed it (I think), can you confirm? Apologies for the late reply, I didn't get online until late today

edit: I was wrong, I didn't fix it before, but now I did... I did additional testing and realized the error was only manifesting in certain situations. a fix will be pushed up in the next couple of minutes

**Comment by jonschlinkert** [comment]
Ok, should be fixed now.

**Comment by jonschlinkert** [comment]
closing due to age and lack of response
